### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jdsika** [dipdup-net/dipdup-py#145]
Hi Team,

I have seen that you have added the MIT license to most other dipdup projects. Is there the intention to add MIT here as well? I would welcome a LICENSE file in the repository if that is the case.
It is important to properly use and attribute your work.

update: found it [here](https://github.com/dipdup-net/dipdup-py/blob/master/pyproject.toml) would be great to actually add the LICENSE text as well as this is the actual license and not the [SPDX short identifier](https://spdx.org/licenses/MIT.html) as it is not clear if you are referring to this.

Best regards
Carlo

**Comment by droserasprout** [comment]
Done! Thanks for the feedback.
