### ISSUE TITLE
`RuntimeError` in `BigMapIndex` after TzKT disconnected by timeout

### ISSUE THREAD

**Issue by veqtor** [dipdup-net/dipdup-py#244]
**Steps to reproduce:**
Use a big map index, wait for connection loss (1-12h)

**What did you expect to happen:**
Not crashing

**What actually happened:**
When connection is lost, and then reestablished, big map index re-runs for current level causing:
`RuntimeError: Level of big map batch must be higher than index state level: 2122233 <= 2122233`

### Environment

* **Python version:** 3.8
* **DipDup version or commit hash: 4.2.4**
* **Database engine version: ?**
* **Hasura version: default in docker file**
* **Are you in docker? yes**
* **Can you reproduce this issue on `master`? not always**

### Attachment checklist

- [x] General: DipDup logs (~100 lines above stacktrace)
[crash.log](https://github.com/dipdup-net/dipdup-py/files/8078978/crash.log)
- [ ] General: `config export` output
- [ ] General: `models.py`
- [ ] SQL issues: `schema export` output
- [ ] Hasura issues: Hasura container logs

**Comment by droserasprout** [comment]
https://sentry.baking-bad.org/organizations/sentry/issues/3578
