### ISSUE TITLE
`TzKTDatasource._level` is None until the first realtime message

### ISSUE THREAD

**Issue by 852Kerfunkle** [dipdup-net/dipdup-py#298]
I think it happens when restarting dipdup without a full reindex.

Not sure this is the correct way to get the current block level, maybe there's a better way to get it from the database maybe?

```
async def on_synchronized(
    ctx: HookContext,
) -> None:
    await ctx.execute_sql('on_synchronized')
    
    level = ctx.get_tzkt_datasource("tzkt_mainnet")._level.get(MessageType.head)
```

**Comment by droserasprout** [comment]
I can add helper method like `tzkt_datasource.get_level(MessageType.head)`. But this number may be incorrect when `--early-realtime` flag is not set - by default, DipDup opens a realtime connection after all indexes are synchronized.

**Comment by 852Kerfunkle** [comment]
Ah, thank you for the hint! Missed that in the docs.

`By default, DipDup enters sync state twice: before and after establishing a realtime connection. This flag allows to start collecting realtime messages while sync is in progress, right after indexes load.`

So I should just be able to tell which sync I'm in by checking level is None? And eventually another `on_synchronized` will be fired.

**Comment by 852Kerfunkle** [comment]
Also, a helper would be convenient, but it's fine as is.

**Comment by 852Kerfunkle** [comment]
Also, I closed the issue early, `DipDup enters sync state twice` - at least not how I'd expect it to.

**Comment by 852Kerfunkle** [comment]
```
tezland-indexer    | INFO     dipdup.tzkt          tzkt_mainnet: Subscribed to 5 channels
tezland-indexer    | INFO     dipdup.index         tezland_mainnet: Index is behind datasource, sync to datasource level: 2269685 -> 2269693
tezland-indexer    | INFO     dipdup.index         tezland_mainnet: Synchronizing index to level 2269693
tezland-indexer    | INFO     dipdup.index         tezland_mainnet: Fetching operations from level 2269685 to 2269693
tezland-indexer    | INFO     dipdup.index         tezland_mainnet: Index is synchronized to level 2269693
tezland-indexer    | INFO     landex.hooks.on_synchronized datasource level is None
tezland-indexer    | INFO     dipdup.tzkt          tzkt_mainnet: Realtime message received: head, DATA, None -> 2269694
tezland-indexer    | INFO     dipdup.tzkt          tzkt_mainnet: Realtime message received: head, DATA, 2269694 -> 2269695
```

After the first realtime message, no `on_synchronized`. Is there a chance to get an `on_realtime` hook maybe?
