### ISSUE TITLE
Hasura configuration error while using ManyToMany field

### ISSUE THREAD

**Issue by Anshit01** [dipdup-net/dipdup-py#440]
**Steps to reproduce:**
Tested this bug on a fresh dipdup project.
- Installation
  ```
  cookiecutter https://github.com/dipdup-net/cookiecutter-dipdup
  make install
  poetry run dipdup init
  ```
- Creating a model with ManyToMany field in `models.py`
  ```
  class Demo(Model):
    id = fields.IntField(pk=True)
    rel = fields.ManyToManyField("models.ExampleModel", related_name="demos")
  ```
- Run using docker compose
  ```
  docker-compose up -d --build
  ```

**What did you expect to happen:**
It should config hasura to expose all models and relationships.

**What actually happened:**
Dipdup fails to configure hasura
- Dipdup error logs
> INFO     dipdup               Hook `on_rollback` is not available
> INFO     dipdup               Initializing database schema
> INFO     dipdup.database      Executing `/home/dipdup/source/src/dipdup/utils/../sql/on_reindex/dipdup_head_status.sql`
> INFO     dipdup.tzkt          tzkt_mainnet: Fetching latest block
> INFO     dipdup.hasura        Configuring Hasura
> INFO     dipdup.hasura        Waiting for Hasura instance to be ready
> INFO     dipdup.hasura        Connected to Hasura v2.8.4
> INFO     dipdup.hasura        Fetching existing metadata
> INFO     dipdup.hasura        Generating Hasura metadata based on project models
> INFO     dipdup.hasura        Found 1 regular and materialized views
> INFO     dipdup.hasura        Replacing metadata
> WARNING  dipdup.http          HTTP request attempt 1/3 failed: 400, message='Bad Request', url=URL('http://hasura:8080/v1/query')
> INFO     dipdup.http          Waiting 1.0 seconds before retry
> WARNING  dipdup.http          HTTP request attempt 2/3 failed: 400, message='Bad Request', url=URL('http://hasura:8080/v1/query')
> INFO     dipdup.http          Waiting 1.0 seconds before retry
> WARNING  dipdup.http          HTTP request attempt 3/3 failed: 400, message='Bad Request', url=URL('http://hasura:8080/v1/query')
> INFO     dipdup.http          Waiting 1.0 seconds before retry
> Traceback (most recent call last):
>   File "/home/dipdup/source/src/dipdup/hasura.py", line 191, in _hasura_request
>     result = await self.request(
>   File "/home/dipdup/source/src/dipdup/http.py", line 59, in request
>     return await self._http.request(method, url, cache, weight, **kwargs)
>   File "/home/dipdup/source/src/dipdup/http.py", line 212, in request
>     return await self._retry_request(method, url, weight, **kwargs)
>   File "/home/dipdup/source/src/dipdup/http.py", line 136, in _retry_request
>     raise e
>   File "/home/dipdup/source/src/dipdup/http.py", line 128, in _retry_request
>     return await self._request(
>   File "/home/dipdup/source/src/dipdup/http.py", line 177, in _request
>     async with self._session.request(
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
>     self._resp = await self._coro
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 640, in _request
>     resp.raise_for_status()
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
>     raise ClientResponseError(
> aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://hasura:8080/v1/query')
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/dipdup", line 5, in <module>
>     cli()
>   File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1157, in __call__
>     return anyio.run(self._main, main, args, kwargs, **opts)
>   File "/usr/local/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
>     return asynclib.run(func, *args, **backend_options)
>   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
>     return native_run(wrapper(), debug=debug)
>   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
>     return await func(*args)
>   File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1160, in _main
>     return await main(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1076, in main
>     rv = await self.invoke(ctx)
>   File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1687, in invoke
>     return await _process_result(await sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1434, in invoke
>     return await ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 780, in invoke
>     rv = await rv
>   File "/home/dipdup/source/src/dipdup/cli.py", line 96, in wrapper
>     await fn(*args, **kwargs)
>   File "/home/dipdup/source/src/dipdup/cli.py", line 282, in run
>     await dipdup.run()
>   File "/home/dipdup/source/src/dipdup/dipdup.py", line 401, in run
>     await self._set_up_hasura(stack)
>   File "/home/dipdup/source/src/dipdup/dipdup.py", line 520, in _set_up_hasura
>     await hasura_gateway.configure()
>   File "/home/dipdup/source/src/dipdup/hasura.py", line 146, in configure
>     await self._replace_metadata(metadata)
>   File "/home/dipdup/source/src/dipdup/hasura.py", line 271, in _replace_metadata
>     await self._hasura_request(endpoint, json)
>   File "/home/dipdup/source/src/dipdup/hasura.py", line 198, in _hasura_request
>     raise HasuraError(f'{e.status} {e.message}') from e
> dipdup.exceptions.HasuraError: Failed to configure Hasura instance
> ________________________________________________________________________________
> 
> Failed to configure Hasura:
> 
>   400 Bad Request
> 
> Check out Hasura logs for more information.
> 
> GraphQL integration docs: https://dipdup.net/docs/graphql/

- Hasura error logs

> {"type":"http-log","timestamp":"2022-08-03T19:31:20.760+0000","level":"info","detail":{"operation":{"request_id":"0efa4bad-875b-476e-a6f6-c928348e51da","response_size":2,"request_mode":"non-graphql"},"request_id":"0efa4bad-875b-476e-a6f6-c928348e51da","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/healthz","ip":"172.23.0.4","method":"GET","content_encoding":null}}}
> {"type":"http-log","timestamp":"2022-08-03T19:31:20.760+0000","level":"info","detail":{"operation":{"query_execution_time":6.724958e-3,"user_vars":{"x-hasura-role":"admin"},"request_id":"04a164c7-cd04-423d-b520-7564dc193745","response_size":1840,"request_mode":"non-graphql","request_read_time":1.795e-4},"request_id":"04a164c7-cd04-423d-b520-7564dc193745","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"172.23.0.4","method":"POST","content_encoding":"gzip"}}}
> {"type":"http-log","timestamp":"2022-08-03T19:31:20.760+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"using":{"foreign_key_constraint_on":{"column":"rel_id","table":{"schema":"public","name":"demo_example_models"}}},"name":"exampleModelsDemos","source":"default","comment":null,"table":{"schema":"public","name":"example_models"}},"reason":"Inconsistent object: in table \"example_models\": in relationship \"exampleModelsDemos\": no foreign constraint exists on the given column(s)","name":"array_relation exampleModelsDemos in table example_models in source default","type":"array_relation"},{"definition":{"using":{"foreign_key_constraint_on":{"column":"demos_id","table":{"schema":"public","name":"demo_example_models"}}},"name":"demoRel","source":"default","comment":null,"table":{"schema":"public","name":"demo"}},"reason":"Inconsistent object: in table \"demo\": in relationship \"demoRel\": no foreign constraint exists on the given column(s)","name":"array_relation demoRel in table demo in source default","type":"array_relation"},{"definition":{"using":{"foreign_key_constraint_on":"demos_id"},"name":"demo","source":"default","comment":null,"table":{"schema":"public","name":"demo_example_models"}},"reason":"Inconsistent object: in table \"demo_example_models\": in relationship \"demo\": no foreign constraint exists on the given column(s)","name":"object_relation demo in table demo_example_models in source default","type":"object_relation"},{"definition":{"using":{"foreign_key_constraint_on":"demos_id"},"name":"exampleModels","source":"default","comment":null,"table":{"schema":"public","name":"demo_example_models"}},"reason":"Inconsistent object: in table \"demo_example_models\": in relationship \"exampleModels\": no foreign constraint exists on the given column(s)","name":"object_relation exampleModels in table demo_example_models in source default","type":"object_relation"}],"path":"$.args","error":"cannot continue due to inconsistent metadata","code":"unexpected"},"request_id":"41a4d0d2-065c-47c2-8e34-1b022b3c2c5e","response_size":1921,"request_mode":"error"},"request_id":"41a4d0d2-065c-47c2-8e34-1b022b3c2c5e","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.23.0.4","method":"POST","content_encoding":null}}}
>   

### Environment

* **Python version:** python = ">=3.10,<3.11"
* **DipDup version or commit hash:** 5.2.5
* **Database engine version:** postgres:14
* **Hasura version:** hasura/graphql-engine:v2.8.4
* **Are you in docker?** yes
* **Can you reproduce this issue on `master`?**
  Haven't tried it, but probably won't work.

**Comment by droserasprout** [comment]
Query:

```json
{
    "type": "replace_metadata",
    "args": {
        "metadata": {
            "version": 3,
            "sources": [
                {
                    "name": "default",
                    "kind": "postgres",
                    "tables": [
                        {
                            "table": {
                                "schema": "public",
                                "name": "dipdup_contract"
                            },
                            "object_relationships": [],
                            "array_relationships": [],
                            "select_permissions": [
                                {
                                    "role": "user",
                                    "permission": {
                                        "columns": "*",
                                        "filter": {},
                                        "allow_aggregations": false,
                                        "limit": 100
                                    }
                                }
                            ]
                        },
                        {
                            "table": {
                                "schema": "public",
                                "name": "dipdup_contract_metadata"
                            },
                            "object_relationships": [],
                            "array_relationships": [],
                            "select_permissions": [
                                {
                                    "role": "user",
                                    "permission": {
                                        "columns": "*",
                                        "filter": {},
                                        "allow_aggregations": false,
                                        "limit": 100
                                    }
                                }
                            ]
                        },
                        {
                            "table": {
                                "schema": "public",
                                "name": "dipdup_head"
                            },
                            "object_relationships": [],
                            "array_relationships": [],
                            "select_permissions": [
                                {
                                    "role": "user",
                                    "permission": {
                                        "columns": "*",
                                        "filter": {},
                                        "allow_aggregations": false,
                                        "limit": 100
                                    }
                                }
                            ]
                        },
                        {
                            "table": {
                                "schema": "public",
                                "name": "dipdup_index"
                            },
                            "object_relationships": [],
                            "array_relationships": [],
                            "select_permissions": [
                                {
                                    "role": "user",
                                    "permission": {
                                        "columns": "*",
                                        "filter": {},
                                        "allow_aggregations": false,
                                        "limit": 100
                                    }
                                }
                            ]
                        },
                        {
                            "table": {
                                "schema": "public",
                                "name": "dipdup_schema"
                            },
                            "object_relationships": [],
                            "array_relationships": [],
                            "select_permissions": [
                                {
                                    "role": "user",
                                    "permission": {
                                        "columns": "*",
                                        "filter": {},
                                        "allow_aggregations": false,
                                        "limit": 100
                                    }
                                }
                            ]
                        },
                        {
                            "table": {
                                "schema": "public",
                                "name": "dipdup_token_metadata"
                            },
                            "object_relationships": [],
                            "array_relationships": [],
                            "select_permissions": [
                                {
                                    "role": "user",
                                    "permission": {
                                        "columns": "*",
                                        "filter": {},
                                        "allow_aggregations": false,
                                        "limit": 100
                                    }
                                }
                            ]
                        },
                        {
                            "table": {
                                "schema": "public",
                                "name": "demo"
                            },
                            "object_relationships": [],
                            "array_relationships": [
                                {
                                    "name": "demoRel",
                                    "using": {
                                        "foreign_key_constraint_on": {
                                            "column": "demos_id",
                                            "table": {
                                                "schema": "public",
                                                "name": "demo_example_model"
                                            }
                                        }
                                    }
                                }
                            ],
                            "select_permissions": [
                                {
                                    "role": "user",
                                    "permission": {
                                        "columns": "*",
                                        "filter": {},
                                        "allow_aggregations": false,
                                        "limit": 100
                                    }
                                }
                            ]
                        },
                        {
                            "table": {
                                "schema": "public",
                                "name": "example_model"
                            },
                            "object_relationships": [],
                            "array_relationships": [
                                {
                                    "name": "exampleModelDemos",
                                    "using": {
                                        "foreign_key_constraint_on": {
                                            "column": "rel_id",
                                            "table": {
                                                "schema": "public",
                                                "name": "demo_example_model"
                                            }
                                        }
                                    }
                                }
                            ],
                            "select_permissions": [
                                {
                                    "role": "user",
                                    "permission": {
                                        "columns": "*",
                                        "filter": {},
                                        "allow_aggregations": false,
                                        "limit": 100
                                    }
                                }
                            ]
                        },
                        {
                            "table": {
                                "schema": "public",
                                "name": "dipdup_head_status"
                            },
                            "object_relationships": [],
                            "array_relationships": [],
                            "select_permissions": [
                                {
                                    "role": "user",
                                    "permission": {
                                        "columns": "*",
                                        "filter": {},
                                        "allow_aggregations": false,
                                        "limit": 100
                                    }
                                }
                            ]
                        },
                        {
                            "table": {
                                "schema": "public",
                                "name": "demo_example_model"
                            },
                            "object_relationships": [
                                {
                                    "name": "demo",
                                    "using": {
                                        "foreign_key_constraint_on": "demos_id"
                                    }
                                },
                                {
                                    "name": "exampleModel",
                                    "using": {
                                        "foreign_key_constraint_on": "demos_id"
                                    }
                                }
                            ],
                            "array_relationships": [],
                            "select_permissions": [
                                {
                                    "role": "user",
                                    "permission": {
                                        "columns": "*",
                                        "filter": {},
                                        "allow_aggregations": false,
                                        "limit": 100
                                    }
                                }
                            ]
                        }
                    ],
                    "configuration": {
                        "connection_info": {
                            "use_prepared_statements": true,
                            "database_url": {
                                "from_env": "HASURA_GRAPHQL_DATABASE_URL"
                            },
                            "isolation_level": "read-committed",
                            "pool_settings": {
                                "connection_lifetime": 600,
                                "retries": 1,
                                "idle_timeout": 180,
                                "max_connections": 50
                            }
                        }
                    }
                }
            ],
            "query_collections": [],
            "rest_endpoints": []
        }
    }
}
```

Response:

```json
{
    "type": "http-log",
    "timestamp": "2022-08-17T16:19:59.053+0000",
    "level": "error",
    "detail": {
        "operation": {
            "user_vars": {
                "x-hasura-role": "admin"
            },
            "error": {
                "internal": [
                    {
                        "definition": {
                            "using": {
                                "foreign_key_constraint_on": "demos_id"
                            },
                            "name": "demo",
                            "source": "default",
                            "comment": null,
                            "table": {
                                "schema": "public",
                                "name": "demo_example_model"
                            }
                        },
                        "reason": "Inconsistent object: in table \"demo_example_model\": in relationship \"demo\": no foreign constraint exists on the given column(s)",
                        "name": "object_relation demo in table demo_example_model in source default",
                        "type": "object_relation"
                    },
                    {
                        "definition": {
                            "using": {
                                "foreign_key_constraint_on": "demos_id"
                            },
                            "name": "exampleModel",
                            "source": "default",
                            "comment": null,
                            "table": {
                                "schema": "public",
                                "name": "demo_example_model"
                            }
                        },
                        "reason": "Inconsistent object: in table \"demo_example_model\": in relationship \"exampleModel\": no foreign constraint exists on the given column(s)",
                        "name": "object_relation exampleModel in table demo_example_model in source default",
                        "type": "object_relation"
                    },
                    {
                        "definition": {
                            "using": {
                                "foreign_key_constraint_on": {
                                    "column": "demos_id",
                                    "table": {
                                        "schema": "public",
                                        "name": "demo_example_model"
                                    }
                                }
                            },
                            "name": "demoRel",
                            "source": "default",
                            "comment": null,
                            "table": {
                                "schema": "public",
                                "name": "demo"
                            }
                        },
                        "reason": "Inconsistent object: in table \"demo\": in relationship \"demoRel\": no foreign constraint exists on the given column(s)",
                        "name": "array_relation demoRel in table demo in source default",
                        "type": "array_relation"
                    },
                    {
                        "definition": {
                            "using": {
                                "foreign_key_constraint_on": {
                                    "column": "rel_id",
                                    "table": {
                                        "schema": "public",
                                        "name": "demo_example_model"
                                    }
                                }
                            },
                            "name": "exampleModelDemos",
                            "source": "default",
                            "comment": null,
                            "table": {
                                "schema": "public",
                                "name": "example_model"
                            }
                        },
                        "reason": "Inconsistent object: in table \"example_model\": in relationship \"exampleModelDemos\": no foreign constraint exists on the given column(s)",
                        "name": "array_relation exampleModelDemos in table example_model in source default",
                        "type": "array_relation"
                    }
                ],
                "path": "$.args",
                "error": "cannot continue due to inconsistent metadata",
                "code": "unexpected"
            },
            "request_id": "24d836af-284a-4ee6-b6da-d554c34ce743",
            "response_size": 1904,
            "request_mode": "error"
        },
        "request_id": "24d836af-284a-4ee6-b6da-d554c34ce743",
        "http_info": {
            "status": 400,
            "http_version": "HTTP/1.1",
            "url": "/v1/query",
            "ip": "172.240.4.1",
            "method": "POST",
            "content_encoding": null
        }
    }
}
```

**Comment by droserasprout** [comment]
@Anshit01, can you check again with `ghcr.io/dipdup-net/dipdup-py:fix-hasura-m2m-again` image?

**Comment by Anshit01** [comment]
@droserasprout, it works!
