### ISSUE TITLE
arm64 Docker image for M1 Macbooks

### ISSUE THREAD

**Issue by droserasprout** [dipdup-net/dipdup-py#447]
Following #358 

[hub.docker.com/r/arm64v8/python](https://hub.docker.com/r/arm64v8/python/)

Blocker: `ruamel.yaml` has no wheels. Need to set up multistage build with compile stage.

**Comment by droserasprout** [comment]
@skenaja, please try the following images:

```
ghcr.io/dipdup-net/dipdup-py:aux-arm64
ghcr.io/dipdup-net/dipdup-py:aux-arm64-pytezos
```

The second one is only if you have additional free time since Idk if anyone uses PyTezos flavor.

**Comment by skenaja** [comment]
@droserasprout I was able to successfully build using both images, so thanks for this!
