### ISSUE TITLE
`TypeError` when calling `init` with non-existent contract in config

### ISSUE THREAD

**Issue by tomsib2001** [dipdup-net/dipdup-py#472]
**Steps to reproduce:**
follow quickstart with dipdup.yml provided in attachment

**What did you expect to happen:**
the normal output of dipdup init
**What actually happened:**
A crash: TypeError: byte indices must be integers or slices, not str

### Environment

* **Python version:**
* 3.10.4
* **DipDup version or commit hash:**
* 6.1.1
* **Database engine version:**
* **Hasura version:**
* **Are you in docker?**
* no
* **Can you reproduce this issue on `master`?**
I haven't tried.

[dipdup-tombstone_qujio8s_.json.txt](https://github.com/dipdup-net/dipdup-py/files/9505948/dipdup-tombstone_qujio8s_.json.txt)
[config_export.txt](https://github.com/dipdup-net/dipdup-py/files/9505958/config_export.txt)
[models.py.txt](https://github.com/dipdup-net/dipdup-py/files/9505964/models.py.txt)

**Comment by tomsib2001** [comment]
I forgot the dipdup.yml file:
[dipdup.yml.txt](https://github.com/dipdup-net/dipdup-py/files/9505978/dipdup.yml.txt)

**Comment by droserasprout** [comment]
The main reason is 204 No Content on https://api.jakartanet.tzkt.io/v1/contracts/KT1EHdK9asB6BtPLvt1ipKRuxsrKoQhDoKgs/interface

Actually, I can't find this contract anywhere, not only on Jakartanet.

**Comment by tomsib2001** [comment]
Oops, sorry about that. Let me check with an actually existing contract..
